#!/bin/bash
ionic cordova build browser --prod
cd ./platforms/browser/www
rsync --exclude=assets/header.js -avz --delete . "eyc_proveedores@newton.eycproveedores.com:htdocs/bagut/documentos" 
fi
echo "syncronized"
cd ../../../